2022-12-05T16:37:46-0300 - __main__ - ERROR - OOPS!! General Error
2022-12-05T16:37:46-0300 - __main__ - ERROR - HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /data/olist_products_dataset.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94905417f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-12-05T16:39:26-0300 - __main__ - ERROR - OOPS!! General Error
2022-12-05T16:39:26-0300 - __main__ - ERROR - HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /data/olist_products_dataset.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94902b9040>: Failed to establish a new connection: [Errno 111] Connection refused'))
